services:
  app:
    build: .
    container_name: loyalty_app
    hostname: loyalty-app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  # Load environment variables from the .env file
    healthcheck:
      test: ["CMD", "curl", "-f", "http://loyalty-app:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: loyalty_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - loyalty_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  loyalty_db_data:
    name: "loyalty_db_data"
